### PR TITLE
Simulate indentation of the project tree using some divs

### LINKED ISSUE #10574: Clicking to left of filename can collapse parent folder
To reproduce:

1. Expand a folder in the project tree which would contain at least one file in it.
2. Click on file at the width of parent's expand triangle (e.g. slightly left to the file name, could be tricky :).

Observed: parent collapses independently of whether file is selected or not.
Expected: if the file is selected, the selection stays. if it's not selected, then selection changes. Parent should not be collapsed.

### PR DESCRIPTION
**Pull request by ficristo**
instead of using combinations of padding/margin.

Fixes #10574

### CODE REVIEW

**Comment by ficristo** [comment]
@petetnt @busykai @nethip 
Could you take a look?

File: src/project/FileTreeView.js [hunk 1]
```diff
@@ -109,6 +111,40 @@ define(function (require, exports, module) {
...
     /**
+     * @private
+     *
+     * Create an appropriate div based thickness to indent the tree correctly.
+     *
+     * @param {int} depth - The depthness of the current node.
+     * @return {ReactComponent} - The resulting div.
+     */
+    function _createThickness(depth) {
+        return DOM.div({
```
Comment (dibosh) [inline src/project/FileTreeView.js]: Does this `div` have defined `display` as `inline-block`?

File: src/project/FileTreeView.js [hunk 2]
```diff
@@ -109,6 +111,40 @@ define(function (require, exports, module) {
...
+            className: "thickness",
```
Comment (dibosh) [inline src/project/FileTreeView.js]: Rather than making it dependant on some css class, wouldn't it be better if we can define all the styles inside `style` property?

File: src/project/FileTreeView.js (hunk 1 above)
Comment (dibosh) [inline src/project/FileTreeView.js]: I just saw it is defined in the `thickness` class, may be we can just define it inside the `style` prop?

**Comment by ficristo** [comment]
@dibosh Thank you to have looked at it.
I think is better to use a class so extension authors can override it.
I use the style only because I need it to be dynamic.
If there is an agreement to use only the style prop is fine by me.

**Comment by ficristo** [comment]
@MarcelGerber if you have a bit of time could you take a look?

File: src/project/FileTreeView.js [hunk 3]
```diff
@@ -109,6 +111,40 @@ define(function (require, exports, module) {
     }
 
     /**
+     * @private
+     *
+     * Create an appropriate div based thickness to indent the tree correctly.
+     *
+     * @param {int} depth - The depthness of the current node.
```
Comment (MarcelGerber) [inline src/project/FileTreeView.js]: Nit, but `depthness` is no word ;)

**Comment by MarcelGerber** [comment]
LGTM, but I'd like to have someone else have a look at the React code (even though it looks straighforward) since I don't know nothing about React.

**Comment by ficristo** [comment]
@MarcelGerber  Thank you.
Maybe @busykai or @petetnt could you take a look?

File: src/project/FileTreeView.js [hunk 4]
```diff
@@ -457,32 +493,40 @@ define(function (require, exports, module) {
...
+                    className: this.getClasses("jstree-leaf"),
+                    onClick: this.handleClick,
+                    onMouseDown: this.handleMouseDown,
+                    onDoubleClick: this.handleDoubleClick
+                },
+                DOM.ins({
+                    className: "jstree-icon"
+                }, " "),
+            ];
+            var thickness = _createThickness(this.props.depth);
```
Comment (petetnt) [inline src/project/FileTreeView.js]: Nit: Consecutive `var`s are usually either separated with a dot or new line

File: src/project/FileTreeView.js [hunk 5]
```diff
@@ -59,6 +59,8 @@ define(function (require, exports, module) {
     var CLICK_RENAME_MINIMUM  = 500,
         RIGHT_MOUSE_BUTTON    = 2,
         LEFT_MOUSE_BUTTON     = 0;
+    
+    var INDENTATION_WIDTH     = 18;
```
Comment (petetnt) [inline src/project/FileTreeView.js]: Should this be configurable? It wasn't with the CSS but could be a nice to have when it's in code.

File: src/project/FileTreeView.js (hunk 2 above)
Comment (petetnt) [inline src/project/FileTreeView.js]: I think I agree with @dibosh's suggestion of just using inline-styles.

File: src/project/FileTreeView.js [hunk 6]
```diff
@@ -109,6 +111,40 @@ define(function (require, exports, module) {
...
+     * @param {int} depth - The depthness of the current node.
+     * @return {ReactComponent} - The resulting ins.
+     */
+    function _createAlignedIns(depth) {
+        return DOM.ins({
+            className: "jstree-icon",
+            style: {
+                marginLeft: (INDENTATION_WIDTH * depth) + "px"
+            }
+        }, " ");
```
Comment (petetnt) [inline src/project/FileTreeView.js]: No need for the second argument (see https://jsfiddle.net/qLLs0ejk/)

File: src/project/FileTreeView.js [hunk 7]
```diff
@@ -457,32 +493,40 @@ define(function (require, exports, module) {
...
+            var liArgs = [
+                {
+                    className: this.getClasses("jstree-leaf"),
+                    onClick: this.handleClick,
+                    onMouseDown: this.handleMouseDown,
+                    onDoubleClick: this.handleDoubleClick
+                },
+                DOM.ins({
+                    className: "jstree-icon"
+                }, " "),
```
Comment (petetnt) [inline src/project/FileTreeView.js]: No need for the second argument (see https://jsfiddle.net/qLLs0ejk/)

File: src/styles/jsTreeTheme.less [hunk 8]
```diff
@@ -46,6 +46,7 @@ li.jstree-closed > ul { display:none; }
 .jstree-brackets .jstree-open > ins { background-position:-72px 0; }
 .jstree-brackets .jstree-closed > ins { background-position:-54px 0; }
 .jstree-brackets .jstree-leaf > ins { background-position:-36px 0; }
+.jstree-brackets .thickness { display: inline-block; }
```
Comment (petetnt) [inline src/styles/jsTreeTheme.less]: See the comment on using inline-styles instead.

**Comment by petetnt** [comment]
Made a few comments :+1:

File: src/project/FileTreeView.js (hunk 5 above)
Comment (ficristo) [inline src/project/FileTreeView.js]: @petetnt If really needed I prefer do it in a different PR.

**Comment by ficristo** [comment]
I've updated the PR.

File: src/project/FileTreeView.js (hunk 5 above)
Comment (petetnt) [inline src/project/FileTreeView.js]: That's fine by me :)

File: src/project/FileTreeView.js [hunk 9]
```diff
@@ -114,35 +114,36 @@ define(function (require, exports, module) {
...
+     * @param {int} depth The depth of the current node.
+     * @return {ReactComponent} The resulting div.
      */
     function _createThickness(depth) {
         return DOM.div({
             className: "thickness",
             style: {
-                width: (INDENTATION_WIDTH * depth) + "px"
+                display: "inline-block",
+                width: INDENTATION_WIDTH * depth
```
Comment (petetnt) [inline src/project/FileTreeView.js]: Unitless value here, does React automatically convert it to `px`?

**Comment by ficristo** [comment]
@petetnt I tryed to remove the unit and it worked...
Now I looked at the [docs](https://facebook.github.io/react/tips/style-props-value-px.html) and if you don't specify the unit most of the styles are automatically converted to use `px`.

**Comment by MarcelGerber** [comment]
@ficristo @petetnt I suppose this is ready to go?

**Comment by petetnt** [comment]
@MarcelGerber LGTM, but has merge conflicts after some recent changes.

**Comment by ficristo** [comment]
I made some changes so to fix the rename case too. So it needs another look.

File: src/project/FileTreeView.js (hunk 5 above)
Comment (MarcelGerber) [inline src/project/FileTreeView.js]: As it turns out in #11717, the indentation should only be 10px, and now that it's merged, that's the behaviour on master, too. I think it looks way cleaner.

**Comment by MarcelGerber** [comment]
Renaming a nested folder doesn't really work.
image

**Comment by ficristo** [comment]
@MarcelGerber I fixed that issue, but now when you rename a folder the element with the children (`ul`) move a little. I wasn't able to find the cause, and I think it is a minor issue.

There is a `renameBehavior` function that should be prevent the directories to collapse, but seems to not work, that's why I've added some more `stopPropagation`.
I don't know enough of react to really look at this problem.

**Comment by MarcelGerber** [comment]
You probably didn't see this comment:
As it turns out in #11717, the indentation (and as such, `INDENTATION_WIDTH`) should only be 10px, and now that it's merged, that's the behaviour on master, too. I think it looks way cleaner.

**Comment by MarcelGerber** [comment]
If you can somehow manage to not apply [`.jstree-rename-input`](https://github.com/adobe/brackets/blob/b1a24ba2665c62ebfd3031f8cf1aa25c233177ed/src/styles/jsTreeTheme.less#L155-L156)'s `top`/`left` rules to the folders, but only to files, we can get rid of the jumping box.

**Comment by ficristo** [comment]
I noticed another small issue were selecting a folder would result in a blue border.
So I reworked the code for render the folder to be more similar to the one of the files: in the renaming case the html layout is a bit different in the sense the input is not anymore in a link tag.
And then hopefully fix the bouncing behaviour: I applyed a style both to folders and files to which doesn't change anything visibily.

**Comment by MarcelGerber** [comment]
LGTM. Going for it.

**Comment by ficristo** [comment]
Thank you @MarcelGerber @petetnt @dibosh for review
