### PR TITLE
Fix #10786 - Allow QuickView image preview for arbitrary URLs

### LINKED ISSUE #10786: Allow QuickView image preview for arbitrary URLs missing image known extension
Currently the code for QuickView's image preview depends on a URL having a known image extension:

```js
            if (/^(data\:image)|(\.gif|\.png|\.jpg|\.jpeg|\.svg)$/i.test(tokenString)) {
```

This is fine in the general case, but falls down when you use an image from a web service.  For example, my gravatar image is https://avatars3.githubusercontent.com/u/427398, which will fail this regex and shows no preview, despite the fact that the image can be loaded correctly.

I think this can be improved.  Since the preview container is not shown until the preview `img` element's `load` event fires, it would be possible to simply try loading a given URL without bothering to check the extension at all.  The current code is:

```js
                  var showHandler = function () {
                        // Hide the preview container until the image is loaded.
                        $previewContainer.hide();
            
                        $previewContainer.find(".image-preview > img").on("load", function () {
                            $previewContent
                                .append("<div class='img-size'>" +
                                            this.naturalWidth + " &times; " + this.naturalHeight + " " + Strings.UNIT_PIXELS +
                                        "</div>"
                                    );
                            $previewContainer.show();
                            positionPreview(editor, popoverState.xpos, popoverState.ytop, popoverState.ybot);
                        });
                    };
```
After setting the `img.src` to the URL, there are two outcomes: a `load` or `error` event.  In the `load` case, the preview would be shown as normal; in the `error` case, `hidePreview()` could be called to cancel the pending preview--this is possibly something that should be done anyway, for the case that an image can't be loaded via the URL (e.g., 404).

Would you consider a patch to do this?

### PR DESCRIPTION
**Pull request by humphd**
This leverages the `img` element's `load` and `error` events to try and load arbitrary images.  It also expands the list of known image extensions to include `.bmp`, which browsers can display.

### CODE REVIEW

**Comment by humphd** [comment]
I've updated this with the suggestion made to examine extensions.

**Comment by MarcelGerber** [comment]
Could you take a look at the data provided by [language.json](https://github.com/adobe/brackets/blob/master/src/language/languages.json)/LanguageManager and see if you can use them? image is particularly interesting for whitelist (please concat "svg" yourself), audio and binary for blacklist (concat the ones you already have, plus maybe also "rss", " xml", "php").

**Comment by humphd** [comment]
I've rewritten this to use `LanguageManager`, good suggestion.

**Comment by humphd** [comment]
This is ready for review.

**Comment by nethip** [comment]
@humphd Can you add some unit tests, if possible? Also run smoke tests with these changes, especially the one relating to editor and Extensions.

File: src/extensions/default/QuickView/main.js [hunk 1]
```diff
@@ -449,67 +450,80 @@ define(function (require, exports, module) {
...
+
+        if (urlMatch) {
+            sPos = {line: pos.line, ch: urlMatch.index};
+            ePos = {line: pos.line, ch: urlMatch.index + urlMatch[0].length};
+        } else {
+            sPos = {line: pos.line, ch: token.start};
+            ePos = {line: pos.line, ch: token.end};
+        }
+
+        var imgPreview = "<div class='image-preview'>"          +
```
Comment (nethip) [inline src/extensions/default/QuickView/main.js]: Could you put in the *imgPath* check here?

**Comment by nethip** [comment]
LGTM

File: src/extensions/default/QuickView/main.js (hunk 1 above)
Comment (humphd) [inline src/extensions/default/QuickView/main.js]: It's already been dealt with in the if-block above from lines 475-483, returning early if we have no value for `imgPath`, and therefore not needing to do the check and indent all this code.

**Comment by redmunds** [comment]
The original Quick View implementation had support for arbitrary URLs, but it was removed due to concerns about performance (i.e. downloading external files on mousemove!). The code has been optimized since then so it now does not try to parse code until mouse hasn't moved for 350ms, but people with a slow network or no network connection might see problems.

Be sure to test this with no internet connection!

You should consider:
1. Making this a preference. It's probably OK to default to ON as long as there's a way to turn it OFF.
2. Caching images. No need to re-download same image over and over. Maybe this already takes advantage of browser cache. Then there's the opposite problem of a stale cache :)

**Comment by humphd** [comment]
I've updated this again.  New commit adds:
* pref for enabling/disabling extensionless previews for URLs (on by default). Let me know if this is how you want such a pref to be done.
* tests for everything that seemed obvious to me about what this patch is doing.

Regarding @redmunds' questions.  First, with no network, you end up in the `error` path (`net::ERR_INTERNET_DISCONNECTED` exception or the like trying to load the resource) and it does the right thing.  I think cache is best handled by the browser.  Trying to build something more intelligent than what is already there fore free seems like a waste of effort to me.

File: src/extensions/default/QuickView/main.js [hunk 2]
```diff
@@ -784,10 +812,15 @@ define(function (require, exports, module) {
 
     // Setup initial UI state
     setEnabled(prefs.get("enabled"), true);
+    setExtensionlessImagePreview(prefs.get("extensionlessImagePreview"));
```
Comment (redmunds) [inline src/extensions/default/QuickView/main.js]: Should never write to prefs on initial load. This is unnecessary and slows down startup. I can see that this is emulating the other pref here, so remove that also if possible.

**Comment by redmunds** [comment]
In general, this looks good. Be sure to turn on JSLint as I am seeing some JSLint errors in QuickView/main.js. Also, there is a merge conflict that needs to be resolved. Just 1 other comment.

File: src/extensions/default/QuickView/main.js (hunk 2 above)
Comment (redmunds) [inline src/extensions/default/QuickView/main.js]: Actually, call to `setEnabled(prefs.get("enabled"), true);` on line above is not writing to prefs, so that should be ok.

Comment (humphd) [inline src/extensions/default/QuickView/main.js]: So the whole `doNotSave` dance was done for the initial load case?  I'll echo that for this as well and avoid the write.

**Comment by humphd** [comment]
@redmunds thanks for the review.  I've rebased and pushed a fixes.  See if this approach satisfies what you wanted with the pref saving and startup.

**Comment by redmunds** [comment]
@humphd 

> See if this approach satisfies what you wanted with the pref saving and startup.

Looks good.

**Comment by humphd** [comment]
Great, can someone land this then?

**Comment by nethip** [comment]
Thanks @humphd for this fix
