### PR TITLE
Fixing update notification locale issue, update notification was shown in English for all locales

### LINKED ISSUE #14994: [EPV] Update Notification not localized on WIN and MAC
### Description
[EPV] Update Notification not localized on WIN and MAC in Brackets 1.14.1

### Steps to Reproduce

1. Launch Brackets 1.14 in French/Japanese.
2. Go to Help->Check for Updates

**Expected behavior:** The Update Notification is localized in the corresponding locales.

**Actual behavior:** The Update Notification is not localized in the corresponding locales.

### Versions
Mac All, Win All
Also reproducible with Brackets 1.13 auto update to Brackets 1.14.

image
image

### PR DESCRIPTION
**Pull request by g-217**
Removing pre-release specific code from release code, as it is causing update notification to be shown in English for all locales.
This will fix https://github.com/adobe/brackets/issues/14994

### CODE REVIEW

File: src/utils/UpdateNotification.js [hunk 1]
```diff
@@ -115,32 +115,6 @@ define(function (require, exports, module) {
             locale = locale.substring(0, 2);
         }
 
-        //AUTOUPDATE_PRERELEASE_BEGIN
```
Comment (shubhsnov) [inline src/utils/UpdateNotification.js]: I think instead of inserting and removing code each time we do a pre-release, we can just check the `update_info_url` to see if it contains pre-release, in which case we default to 'en' otherwise go with the release method of adding URL params

**Review by shubhsnov — CHANGES_REQUESTED** [review]

File: src/utils/UpdateNotification.js (hunk 1 above)
Comment (jha-g) [reply src/utils/UpdateNotification.js]: Changed URL `update_info_url` format to address the issue.

**Comment by jha-g** [comment]
@niteskum

**Review by swmitra — APPROVED** [review]
LGTM

**Comment by shubhsnov** [comment]
👍 LGTM
