### PR TITLE
Fix crawlComplete exception when running tests

### LINKED ISSUE #12658: Exception in 'crawlComplete' listener
Running some tests I see the following exception. I'm starting to think it's becoming important to fix because I've the impression it affects the tests results.
```js
EventDispatcher.js:235 Exception in 'crawlComplete' listener on NodeDomain {connection: NodeConnection, _domainName: "FindInFiles", _domainPath: "C:/Program Files (x86)/Brackets/dev/test/../src/search/node/FindInFilesDomain", _domainLoaded: true, _connectionPromise: null…} TypeError: Cannot read property 'name' of null TypeError: Cannot read property 'name' of null
    at nodeFileCacheComplete (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/search/FindInFiles.js:99:58)
    at NodeDomain.trigger (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/utils/EventDispatcher.js:233:40)
    at Object.triggerWithArray (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/utils/EventDispatcher.js:271:28)
    at NodeDomain.<anonymous> (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/utils/NodeDomain.js:143:41)
    at NodeConnection.trigger (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/utils/EventDispatcher.js:233:40)
    at Object.triggerWithArray (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/utils/EventDispatcher.js:271:28)
    at NodeConnection._receive (file:///C:/Program%20Files%20(x86)/Brackets/dev/src/utils/NodeConnection.js:479:29)
```

Related to https://github.com/adobe/brackets/issues/12634

/cc @abose @MarcelGerber

### PR DESCRIPTION
**Pull request by marcelgerber**
Fixes #12658. (cc @ficristo)

Turns out the fix is quite straightforward.

### CODE REVIEW

**Comment by ficristo** [comment]
The change itself LGTM, but I'm not sure if instead we should always have the project name at this point in the code.
Maybe @abose knows.

File: src/search/FindInFiles.js [hunk 1]
```diff
@@ -96,7 +96,12 @@ define(function (require, exports, module) {
     }
 
     function nodeFileCacheComplete(event, numFiles, cacheSize) {
-        var projectName = ProjectManager.getProjectRoot().name || "noName00";
+        var projectName = ProjectManager.getProjectRoot();
```
Comment (petetnt) [inline src/search/FindInFiles.js]: Small nit / bikeshedding: instead of assigning the return value `getProjectRoot()` to `projectName`, it could be a bit cleaner if it was something like:

```
var projectRoot = ProjectManager.getProjectRoot();
var projectName = projectRoot ? projectRoot.name : null;

if (!projectName) {
  projectName = "noName00";
}
```

In general I think that there should never be an situation where `projectRoot.name` is empty anyways until Brackets supports opening up with no projects at all.

**Comment by petetnt** [comment]
I agree with @ficristo, there really shouldn't be any situation where there wasn't a `projectRoot` but the search was running, should there?

**Comment by MarcelGerber** [comment]
To me, it looks like the Node instance sends the event both to the test window and the Jasmine window, where obviously, no project is loaded. So it runs fine in the test window, but throws this exception in the parent Test Runner window.

**Comment by ficristo** [comment]
@MarcelGerber to me you are the expert so if you think is fine it's ok for me.
But would be nice, if possible, to add at least a log or something in the unexpected case:
```
if no project name then
  if not test window then
    log "unexpected"
  end
  projectname = NoName00
end
```

**Comment by MarcelGerber** [comment]
So, I just made sure my assumption that both the Test Runner and the test window get sent an event in this case, and the Test Runner cannot handle it properly. I'm not sure whether it's the same event though (I think it is).

One way would be (assuming it is one event) for the Test Runner to ignore all Node events it is being sent, which is definitely the more general solution and may prevent other issues as well. On the other hand, I'm not sure if some Node events are expected for tests to pass.
Also, I'm not quite sure how to know whether the current window is the Test Runner or not.

I'll look into it.

**Comment by MarcelGerber** [comment]
So, it turns out the SpecRunner definitely needs to receive Node events.
I updated the PR to have it ignore just this event.

File: src/search/FindInFiles.js [hunk 2]
```diff
@@ -93,7 +93,19 @@ define(function (require, exports, module) {
     }
 
     function nodeFileCacheComplete(event, numFiles, cacheSize) {
-        var projectName = ProjectManager.getProjectRoot().name || "noName00";
+        if (/\/test\/SpecRunner\.html$/.test(window.location.pathname)) {
```
Comment (ficristo) [inline src/search/FindInFiles.js]: Would be nice to check for the `/brackets/i` regex too. But I don't know the location on the other OS.

File: src/search/FindInFiles.js [hunk 3]
```diff
@@ -93,7 +93,19 @@ define(function (require, exports, module) {
...
+            // Ignore the event in the SpecRunner window
+            return;
+        }
+
+        var projectRoot = ProjectManager.getProjectRoot(),
+            projectName = projectRoot ? projectRoot.name : null;
```
Comment (ficristo) [inline src/search/FindInFiles.js]: Could you add a console.error if we don't have the `projectRoot`?

**Comment by ficristo** [comment]
I left a couple of comments, but otherwise LGTM.
@petetnt needs to check too.

File: src/search/FindInFiles.js (hunk 3 above)
Comment (MarcelGerber) [inline src/search/FindInFiles.js]: If we don't have the project root, projectName is null and thus we get the error message below.

File: src/search/FindInFiles.js (hunk 2 above)
Comment (MarcelGerber) [inline src/search/FindInFiles.js]: We cannot be certain what the git clone is named on the system. Also, it's very likely that a Brackets Shell window that has a SpecRunner.html loaded, which in turn loaded the rest of Brackets, actually belongs to Brackets ;)

File: src/search/FindInFiles.js (hunk 3 above)
Comment (ficristo) [inline src/search/FindInFiles.js]: Ah, I should not review code when I'm tired...

**Comment by petetnt** [comment]
LGTM too :+1:
